### ISSUE TITLE
Broken Theme on Sublime Text

### ISSUE THREAD

**Issue by vanyamil** [material-theme/vsc-material-theme#1256]
**Describe the bug**
The theme is broken now on packagecontrol.io

**To Reproduce**
1. Try to download and use the theme "Material Theme" on Sublime Text

**Expected behavior**
Works as before, rather than automatically reset to default.

**Comment by colethorsen** [comment]
I'm having the same issue. I'm guessing an auto update happened, there was an error message that flashed up, and then the color scheme reverted tot he default. The material theme is removable and re-installable but the themes are no longer listed.

**Comment by User123698745** [comment]
Also stopped working for me on Sublime Text 3. I got this error message:
> The package containing your active theme was just upgraded, however the .sublime-theme file no longer exists. Sublime Text has been configured use the default theme instead.

**Comment by AtditC** [comment]
> Also stopped working for me on Sublime Text 3. I got this error message:
> 
> > The package containing your active theme was just upgraded, however the .sublime-theme file no longer exists. Sublime Text has been configured use the default theme instead.

I also got the same error on Sublime Text 4 on Arch Linux, installed via the AUR package. Reinstalling the theme or the whole Sublime Text package didn't help.

**Comment by raphaelsk** [comment]
My quick read is that the repository with the Material Theme for Sublime Text has been deleted (or made private), and Package Control was updated to point to this VS Code theme repository. Package Control then auto-generated a zip/sublime-package from this VS Code repo, and all our machines auto updated.
Sadly, VS Code themes do not (generally) work in Sublime Text.

**Comment by TurboBoard** [comment]
Same.

**Comment by ervilsoft** [comment]
Same issue here.

**Comment by Brugman** [comment]
Same issue. Please undo this.

**Comment by lexakimov** [comment]
Got same issue.

**Comment by lxShaDoWxl** [comment]
Тоже столкнулся с этой проблемой =(
Решил её с помощью ручной установки пакета в subl, скачать пакет можно тут
https://github.com/lxShaDoWxl/material-theme/releases/tag/v4.1.5

**Comment by vanyamil** [comment]
For those interested in restoring it:
First, go to Sublime and disable auto-updates and install-missing options in Package Control settings

```
	// If packages should be automatically upgraded when ST starts
	"auto_upgrade": false,

	// If missing packages should be automatically installed when ST starts
	"install_missing": true,
```

Then, put the file linked above in the location of your packages. On Windows, it's in %appdata%/Sublime Text/Installed Packages

**Comment by Krukar** [comment]
They won't be fixing this: https://twitter.com/materialtheme/status/1598567199756656640

**Comment by yangchen5710** [comment]
Same issue. Please undo this.

**Comment by Gerst20051** [comment]
You can update to use the `Materialize` theme instead! Enjoy!! 🕺 🚀 🔥

https://github.com/saadq/Materialize
https://github.com/saadq/Materialize-Appbar

```
{
	"installed_packages":
	[
		"Materialize",
		"Materialize-Appbar"
	]
}
```

```
{
	"color_scheme": "Packages/Materialize/schemes/Material Oceanic Next.tmTheme",
	"theme": "Material Oceanic Next.sublime-theme"
}
```

<img width="918" alt="Screen Shot 2022-12-02 at 12 33 35 AM" src="https://user-images.githubusercontent.com/235372/205250528-7028bd22-27df-4459-abac-dc78aeb52c10.png">

**Comment by ADDISON74** [comment]
I confirm the issue. Reinstall in vain because Package Control no longer gets all the files necessary to run. It is inadmissible under the pretext of lack of maintenance to generate errors in use based on deleting files. There are tons of ST3 packages that are no longer maintained, but no developer has acted like the Material Theme team. even if it is a proprietary code, what happened today is not ethical towards all users of this package. I will uninstall it and I will stop using it in other IDEs even if it is maintained (Visual Code, Phpstorm).

**Comment by mallowigi** [comment]
The JetBrains versions of the plugin is not affiliated with this theme or the author in any way.

Besides, plugin depreciation is a thing. Don't blame the author for not wanting to continue managing a dead plugin. Either fork it or move along. There are plenty of other themes available.

**Comment by ergonomicus** [comment]
Nobody is blaming the author for not wanting to continue managing a plugin, it was a case for years now, but he could just leave it as it was yesterday, right? We are here to rant, so either join or move along. :)

**Comment by DroidFreak32** [comment]
> Тоже столкнулся с этой проблемой =( Решил её с помощью ручной установки пакета в subl, скачать пакет можно тут https://github.com/lxShaDoWxl/material-theme/releases/tag/v4.1.5

Gotta love Open Source for this very reason! Theme is now restored, thanks!

**Comment by ADDISON74** [comment]
@mallowigi - I do not in any way force the author to continue the work. On the contrary, I respect it but the approach was totally wrong. To start ST today and have error messages, deleted files, to be asked to make changes, was not ethical at all. Was it difficult to publish a message and leave the package in unmaintained? I think he had more to gain, he would have received many thanks.

However, let's not forget that the success of Material Theme was also due to Sublime Text users. There are tons of articles about Sublime Text where this package is mentioned.  I did not like the statement of the author from today on Twitter "Is enough". Maybe the programmers should also take communication courses.

**Comment by mallowigi** [comment]
I too believe that he could have better communication with his users but you have to know one thing: he, or me for that matter, have no obligations towards other people. It was always clear that this project or any open source project, could stop anytime. It would be bad for the reputation of the author, yes, but if it's something he is ok with, there's nothing you can do about that.

Fortunately you can fork the project and build your own version, especially if the author cannot provide his own alternative. That's what people did in vsc and provided a "community theme" to fork from the author's theme.

It's a difficult day, I'm also a user of the MT for the days I use Sublime and I will always be grateful to Matteo for what he did. But all things come to an end and you have to respect that.

**Comment by Aldaviva** [comment]
> For those interested in restoring it: First, go to Sublime and disable auto-updates and install-missing options in Package Control settings
> 
> ```
> 	// If packages should be automatically upgraded when ST starts
> 	"auto_upgrade": false,
> 
> 	// If missing packages should be automatically installed when ST starts
> 	"install_missing": true,
> ```
> 
> Then, put the file linked above in the location of your packages. On Windows, it's in %appdata%/Sublime Text/Installed Packages

Alternatively, if you want to prevent Package Control from auto-upgrading just this package instead of all your packages, you can set `auto_upgrade_ignore` in `%appdata%\Sublime Text 3\Packages\User\Package Control.sublime-settings`:

```json
"auto_upgrade_ignore": [
    "Material Theme"
],

**Comment by FichteFoll** [comment]
As an immediate action to mitigate user setups breaking, I have removed the "Material Theme" from the Package Control package index. It will be gone from the cache within the next hour and won't be updated for any users anymore.

To this date, the package is the 12th most installed package on Sublime Text despite it not being maintained for 6 years because it supposedly never broke (since ST aims to maintain backwards compatibility for quite some time) and is probably recommended in many places such as articles. Removing a working package "just because" is outright rude to say the least. There would have been better ways to handle this, such as archiving the repository instead. It's not like people looking for a Sublime Text theme would be happy when they instead were redirected to a VS Code theme and vice versa.

**Comment by karolyi** [comment]
@FichteFoll, thanks for the quick fix.

I was also totally surprised by my theme breaking today when getting the "autoupdate". This is not a way to deal with open source development. The old package should have stayed untouched, with an end-of-life notice added to it.

**Comment by audetcameron** [comment]
I too woke up to a broken theme in sublime text   build 4142

**Comment by kevnk** [comment]
Here's what worked for me (combining a couple of the comments above, plus I'm adding some details from [the old README.md](https://github.com/lxShaDoWxl/material-theme/blob/v4.1.5/README.md)):

1. Add Package Control settings to not auto-update this package ([comment](https://github.com/material-theme/vsc-material-theme/issues/1256#issuecomment-1335106816))
2. Download https://github.com/lxShaDoWxl/material-theme/releases/tag/v4.1.5 ([comment](https://github.com/material-theme/vsc-material-theme/issues/1256#issuecomment-1334748285))
3. Unzip and Rename folder to "Material Theme" and place in "Packages" folder ([Readme instructions](https://github.com/lxShaDoWxl/material-theme/blob/v4.1.5/README.md#manual-installation))
4. Open Package Control panel and type "Material Theme: Activate Theme" ([Readme instructions](https://github.com/lxShaDoWxl/material-theme/blob/v4.1.5/README.md#activate-the-theme))

**Comment by ergonomicus** [comment]
> Here's what worked for me (combining a couple of the comments above, plus I'm adding some details from [the old README.md](https://github.com/lxShaDoWxl/material-theme/blob/v4.1.5/README.md)):
> 
> 1. Add Package Control settings to not auto-update this package ([see this comment](https://github.com/material-theme/vsc-material-theme/issues/1256#issuecomment-1335106816))
> 2. Download https://github.com/lxShaDoWxl/material-theme/releases/tag/v4.1.5 ([thanks to this comment](https://github.com/material-theme/vsc-material-theme/issues/1256#issuecomment-1334748285))
> 3. Unzip and Rename folder to "Material Theme" and place in "Packages" folder ([Readme instructions](https://github.com/lxShaDoWxl/material-theme/blob/v4.1.5/README.md#manual-installation))
> 4. Open Package Control panel and type "Material Theme: Activate Theme" ([Readme instructions](https://github.com/lxShaDoWxl/material-theme/blob/v4.1.5/README.md#activate-the-theme))

Exactly what I did, everything is back to normal now.

**Comment by equinusocio** [comment]
We never saw so much feedback and user activity during the whole life of the project (10 years). 

7 years ago we deprecated and informed everyone. Deprecation means move away from it asap, we think 7 years are enough and we don't want to provide harmful software anymore (many dependency of that project had/and still have security issues). 

Then, open source doesn't mean work for free, and since we get paid and supported by the extension for VsCode we want to focus on that as main project. 

Lastly, we just transferred the popularity of the original theme to the main one for vs code. 

That’s all, folks. Gently remind don’t use recovered repositories since that project includes vulnerabilities. 

I am closing this since it is not a bug or the right place. For questions, there is the discussions page.
