### ISSUE TITLE
After vscode 1.80 version,The parameter hint has changed from the original gray to the same white as the code font

### ISSUE THREAD

**Issue by EvilMoOd** [material-theme/vsc-material-theme#1272]
**Describe the bug**
After vscode 1.80 version, when turn on the parameter hint, the parameter color changes from the original gray to white. This problem will not appear in the version before 1.79. I hope to change the color back to the original gray, which is good for my code Very helpful reading, thanks a lot

**Screenshots**
Before vscode 1.80 version
![f472121bb210f96fb0a9bd81e35909d](https://github.com/material-theme/vsc-material-theme/assets/98245255/ca3c1fd7-8430-47c7-99d8-00cc41039ecd)
after vscode 1.80 version
![2d9f7f2d7ce052bdc45851548822d40](https://github.com/material-theme/vsc-material-theme/assets/98245255/22cb8dec-0558-4349-b045-545887ebdda0)
It's hard to tell if it's real code or a parameter hint

**To Reproduce**
1. open settings
2. enabled inlay hints>Parameter Names
![image](https://github.com/material-theme/vsc-material-theme/assets/98245255/4f1e9672-1407-4544-ae22-0a4d505d59d2)
3. Write a function with parameters like above

**Expected behavior**
I hope to see that the color of the parameter hintcan be less obvious than before, at least it can be distinguished from the real code color

**Additional context**
I am useing Darker Theme

**Comment by ArmorDarks** [comment]
It is reproducible for me too, no extensions interfering with colors or syntax

**Comment by equinusocio** [comment]
Hello, we can't reproduce the issue with vscode 1.82. Please make sure you're using the correct and official material theme extension and not the "community maintained" which was deprecated years ago and that we don't support since then.

![CleanShot 2023-09-10 at 14 48 44](https://github.com/material-theme/vsc-material-
theme/assets/10454741/ff90c767-70cb-4e06-96f2-86cc0c1dc6f5)

**Comment by ArmorDarks** [comment]
Thanks for checking @equinusocio 

In my case, it's an [official extension](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme). Community extension not installed. VS Code 1.81.1 (Universal), MacOS Ventura 13.3 (22E252)

All hints in JS and TypeScript having wrong color too 

<img width="1051" alt="image" src="https://github.com/material-theme/vsc-material-theme/assets/4460311/fb513d5a-255c-4720-ae8c-b97fd7a59b36">

Checked settings.json - no color overrides there.

**Comment by ArmorDarks** [comment]
Just to be sure, I tried with all extensions disabled + VS Code reload. Hint color still wrong:

<img width="1724" alt="image" src="https://github.com/material-theme/vsc-material-theme/assets/4460311/a1c44bf9-48b6-44c6-99f6-a9537ade57c4">

**Comment by ArmorDarks** [comment]
Updating to VS Code 1.82 fixed the issue 👍 

However, either I remember it wrong, or the color is not the one that's defined in the Material Theme.

Color in 1.82

<img width="710" alt="image" src="https://github.com/material-theme/vsc-material-theme/assets/4460311/f5e02ab5-2e6e-4adb-a06c-327f640bee92">

Color prior to 1.80

![image](https://github.com/material-theme/vsc-material-theme/assets/4460311/5c17e656-b804-4bb3-afac-8b01225d57f5)

**Comment by equinusocio** [comment]
We didn't change any syntax colors in recent updates, so it's probably caused by semantic highlighting. Check the following setting, MT set semantic highlighting (the new way released months ago) to true by default, if you don't like it you can disable it.

Just keep note that this setting is just about how vscode assigns scopes to code elements, we have no control over this.

![CleanShot 2023-09-11 at 10 00 21](https://github.com/material-theme/vsc-material-theme/assets/10454741/0d7cd93f-160a-4795-9ef8-7f9c45d8c247)
