### ISSUE TITLE
Command pallet colors are difficult to see

### ISSUE THREAD

**Issue by azzazkhan** [material-theme/vsc-material-theme#1273]
VS Code showed me notification of the deprecation of **Community Material Theme** and the extension's details linked to this repo and I installed the new **Material Theme** extension and it had all the themes of old extension (I use **Hight Contrast**) though when I opened the command pallet (Ctrl + Shift + P \ Ctrl + P) the colors are too soft and the text is difficult to read previous extension had darker colors which were easier to read.

![image](https://github.com/material-theme/vsc-material-theme/assets/25636920/7d2511ef-e9e8-4c56-96cb-5b307dec199e)

**Comment by VladimirMikulic** [comment]
I have the same experience for Palenight High Contrast. Material Theme is different from the community one (which I prefer).

**Comment by jamesbellnet** [comment]
I also had this issue so I've forked the original repo and re-released it on the marketplace [here](https://marketplace.visualstudio.com/items?itemName=jamesbellnet.vsc-legacy-community-material-theme).

**Comment by michaeltroya** [comment]
I've noticed many issues compared to Community Material Theme 🥲

@jamesbellnet just installed thanks!

**Comment by azzazkhan** [comment]
Previously it showed traits in yellowish shade but now it's in plain white. It makes it bit difficult to work as I'm used to the previous color schemes.

![image](https://github.com/material-theme/vsc-material-theme/assets/25636920/97188142-cc4c-48ba-9ca3-72f162c8c9a1)

**Comment by azzazkhan** [comment]
@VladimirMikulic Thanks bro for the extension!

**Comment by VladimirMikulic** [comment]
@azzazkhan @jamesbellnet created the extension, not me :)

**Comment by dmyers** [comment]
Yeah I don't fully understand why the change to deprecate the community theme when the official one hasn't had many updates and seems way less polished. 😞

**Comment by equinusocio** [comment]
Community Material Theme is obsolete, it was the very first version of the theme since 2016 and never updated. It doesn't support vscode features from the last 4 years (like semantic highlighting). You ppl should learn how to work with open-source projects and read README files, [there is a whole section about how to customize the theme](https://github.com/material-theme/vsc-material-theme?tab=readme-ov-file#override-theme-colors), while supporting the project, instead of releasing cloned extensions.

There are people working for free on this open-source project, you're just disrespectful.
