### ISSUE TITLE
The new syntax colors are strange [31.1.0]

### ISSUE THREAD

**Issue by daniandl** [material-theme/vsc-material-theme#410]
Is it normal that everything is now mostly blue or red?
I guess I'll have to rock my own theme once the legacy ones are gone 😢 

![image](https://user-images.githubusercontent.com/2960785/71843695-bebcf800-30c4-11ea-8b66-73513db1e207.png)

**Comment by jarrodmedrano** [comment]
I thought it was just me.
Was this update a mistake? It looks really weird. Oceanic is almost unrecognizable.

![Screen Shot 2020-01-06 at 12 50 39 PM](https://user-images.githubusercontent.com/1929136/71844350-29e5da80-3083-11ea-935f-3fbc022a5400.png)

**Comment by jhpratt** [comment]
Personally I think this change is a mistake. The new colors are barely distinguishable.

Frankly, if this isn't reverted, I'll use a different theme.

**Comment by williams-brian** [comment]
You can get the old colors back by selecting the theme as "Legacy - <Your material theme>".

I agree that I don't like the new color scheme at all. It's odd that such a large change isn't accompanied by an announcement or release notes.

**Comment by jhpratt** [comment]
@williams-brian It is noted in the release notes, though it should be far more prominent. Adding a "legacy" option only kicks the can down the road.

**Comment by jarrodmedrano** [comment]
The legacy theme does not look the same as it used to either.

**Comment by jlpereira** [comment]
I dont like too much the new schema too, I hope this was a mistake. But for the moment it's possible select the old one.

**Comment by equinusocio** [comment]
Hi, We announced new color schemes [almost 6 months ago](https://twitter.com/materialtheme/status/1147542082342588416?s=20) on our [twitter profile](https://twitter.com/materialtheme) (which suggest you to follow ) and on Github through issues.

This change is introduced to solve many other issue related to the schemes maintainability since old schemes and builder were too old and buggy. The new introduced generator allow us to improve, update and fix schemes more easily and with less time. We also wanted to simplify schemes scopes declarations, **so this drove us to completely redesign schemes.** 

The new schemes are a fresh start for this theme and, obviously, they may require fixes. As mentioned above, old and "locked" schemes are still available, but they will not get more updates.
