### ISSUE TITLE
Let, Const, Function, Arrow Function  are in Grey Color

### ISSUE THREAD

**Issue by GulajavaMinistudio** [material-theme/vsc-material-theme#413]
**Describe the bug**
Some variable and operator color looks grey and low readibility  in JavaScript File.

**To Reproduce**
1. Change to Material Theme Palenight or Ocean with Dark Theme

**Expected behavior**
Some element should have distinct color and easy to read if applied to large codebase 

**Screenshots**
![code](https://user-images.githubusercontent.com/11639412/71856287-0f107600-3116-11ea-8a49-641fea9827a9.png)

**Additional context**
Variable color such as Let, Const, Function, and Arrow Function color is greyed out. We cannot distinct or low readability when scrolling large code base. Can you change it with bright or vivid color ? such as orange or some vivid color, from this material color palette ? 
[https://material-ui.com/customization/color/](https://material-ui.com/customization/color/)

**Comment by michaelelliot** [comment]
Until this is fixed try using one of the legacy themes (e.g. "Legacy - Material Theme Darker").

**Comment by equinusocio** [comment]
This is intentional. The grey color is..a color. We don't want to make storages and functions keywords to be invasive and we boost focus on the keywords value (variable and function names are in yellow for this reason)

Since this reflect a personal taste and not a real issue, we suggest you to check this README section about customising Material Theme.
https://github.com/material-theme/vsc-material-theme#override-theme-colors

or, as suggested by @michaelelliot, you can switch back to legacy themes.

**Comment by haydencrain** [comment]
@equinusocio are you able to give a timeframe as to when the Legacy themes will be removed entirely?

**Comment by equinusocio** [comment]
Probably next year. We need time to polish new schemes.
