### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by rob-bisson** [material-theme/vsc-material-theme#415]
I'm not quite sure this is for you, or something that's changed in an update. But my material theme has changed. My colours were updated, and I noticed that the new Legacy versions use pink instead of the darker red/orange colour. I was very happy with how it was, I'm curious if you guys pushed out any changes that altered this and why it was done?

Typically if you have a lot of people using your software in a configuration and that changes, it is not a great user experience, especially if they can't get back to where they were. 

That said, I have really loved using your theme up until this point, it was the only dark theme I enjoyed using. If this isn't something on your end, I apologize, just take my praise :)

<3

**Comment by mallowigi** [comment]
As the maintainer of the Material Theme for JetBrains, I can understand both parties. Basically as the maintainer of the project, I can decide whatever features I want to add without having to consult for the general public. Unless you're not under contract, you can do whatever you want, and since it's free, users have no right to complain.

This being said, if you have a lot of users, you should not making drastic changes without giving them at least a way to keep the old behavior back. Otherwise users will simply leave for better alternatives. But then you can decide that it's a sacrifice that need to be made. If on the basis of 1 million users, only 100 users complain and churn, you would still get 999900 users. On the other hand if you have 1000 users and 199 are unhappy it will be bad for your reputation.

In any case, I don't really understand the reason for such changes, some are not really UX-friendly, but more importantly it is disrupting the flow that so many of us were used to. Suddenly attributes are purple, function names are red and css properties and rules are yellow. It is a nightmare for muscle memory, and should not be taken lightly. 

But again if you think this change is absolutely necessary and present the right arguments for such a change, then the users will have to adapt. On the other hand if you just say "it's my theme i can do whatever the f*ck I want and if you don't like it you're welcome to f'ck off", then your adaptation rate will sure to drop, not only from regular users but new users as well.

Then again, you have the right to delete the repository as well.

**Comment by OctoD** [comment]
Hint: you now have  legacy material themes installed, you could use them if the new color schemes do not fit 

![image](https://user-images.githubusercontent.com/2328211/71912883-a2799380-3176-11ea-9225-1f79c1e5059a.png)

**Comment by equinusocio** [comment]
Hi @rob-bisson, as previously announced, we released new schemes (that are discussed here #412 #411 #410).

New schemes are the new "default" and old schemes are still available, you should see them in the themes list with a **Legacy -** prefix. Please also check latest `v31.5` release, we've release some fixes.

**Comment by SharpMobileCode** [comment]
> Hint: you now have legacy material themes installed, you could use them if the new color schemes do not fit
> 
> ![image](https://user-images.githubusercontent.com/2328211/71912883-a2799380-3176-11ea-9225-1f79c1e5059a.png)

It's been stated multiple times, and in the release notes, that Legacy themes will be "deleted sooner or later".  Would you all consider not deleting these at all and let the community maintain the Legacy themes while the Contributors maintain the new themes?  I also develop and maintain a mobile app that is 100% for users and I get zero to little contribution so I understand your position.  I think most people would like to continue to use  legacy indefinitely.

**Comment by rob-bisson** [comment]
@equinusocio really appreciate the reply. I am happy that the legacy theme is remaining. Thanks for taking the time out to reply!

**Comment by equinusocio** [comment]
@rob-bisson Thank you for your suggestion, we're open to evaluate this, but since the first version for Sublime Text, this theme never got contributions from the community. If someone want to maintain/fix legacy schemes we can accept it, but they will still remain flagged as legacy, while the new themes are the ”official ones". This is for consistency.

If we'll not get updates and intentions from the community, legacy themes will probably be removed next year.
