### ISSUE TITLE
Legacy - Material Theme Darker High Contrast has wrong variable color

### ISSUE THREAD

**Issue by GisliNielsen** [material-theme/vsc-material-theme#421]
The red color for variables has changed. Any chance og getting the original red back?

Example of it happening
const test = 'test';
The variable name test will be pinkish instead of red.

**Comment by equinusocio** [comment]
This seems unrelated to our theme since our themes (legacy and not) doesn't apply a red color on variables from 2017. That's how variables look from 2017. 

That's is what you should see.

<img width="224" alt="Screenshot 2020-01-08 at 11 11 49" src="https://user-images.githubusercontent.com/10454741/71969816-be794580-3207-11ea-9a7a-bff55e5912c4.png">

Your issue is probably related to some language extension.

**Comment by GisliNielsen** [comment]
You are correct that I am talking about javascript. I tried to disable all of my other extensions, but it still happens to be pinkish. I double checked and I am indeed using the correct theme

![image](https://user-images.githubusercontent.com/17725274/71970736-8bd04c80-3209-11ea-8aad-8519e7dda192.png)

**Comment by equinusocio** [comment]
OK we figure it out. The default vscode built-in javascript extension offer a poor highlight and it assign a non-precise scope to your code. We suggest you to use advanced highlight extension for javascript in order to improve the highlight. We suggest to use this one.

https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel

**Comment by GisliNielsen** [comment]
While this did fix this variable name, the colors are still a bit off. As you can see for objects, the key has a green color. Also, react jsx syntax is also pinkish
![image](https://user-images.githubusercontent.com/17725274/71973858-511de280-3210-11ea-900f-e4785a49dfb7.png)

**Comment by equinusocio** [comment]
Exactly, that's the default behaviour of our themes. Non changes were made.

**Comment by evaera** [comment]
There were changes made. The "Legacy" Darker High Contrast theme doesn't use the same colors as it did previously. 

![image](https://user-images.githubusercontent.com/2489210/71992415-5a548280-3203-11ea-8062-772e6b54a4db.png)

As mentioned in #422, the tags are a much pinker shade of red.

**Comment by SharpMobileCode** [comment]
But I think the Legacy values were updated.  @equinusocio, could this have been an accidental Find/Replace all?  The color before/after hex values are consistent to what @evaera has pointed out.

https://github.com/material-theme/vsc-material-theme/commit/1c45722680b6bad2803acdc1384acb8503f300d3#diff-301730f92fb1a93ef8d2f2273e459a10

**Comment by equinusocio** [comment]
@SharpMobileCode we replaced the whole schemes, just the time to test them and we'll release the fix. Thank you.
