### ISSUE TITLE
No preview image

### ISSUE THREAD

**Issue by puttehi** [material-theme/vsc-material-theme#576]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add image(s) previewing what the theme looks like.

**Describe alternatives you've considered**
Not installing the theme.

**Additional context**
I can't be the only one that thinks that the most important thing in a themes README is the previews of what it looks like.
It comes across as a cheap way to boost download numbers by making people check it out themselves.

**Comment by equinusocio** [comment]
Hello, Material Theme has multiple variants to preview, we decided to not add images to the (already bloated) README file. 

If VSCode supports the `details` element we can now consider adding images into a collapsed section, otherwise the main way to check the preview is through the website https://material-theme.site/
